on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 173.201.190.138
          username: louie@bucklandhauntedfarm.com
          password: ${{ secrets.ftp_password }}
